epi052/recon-pipeline

- recon-pipeline.py
- recon/__init__.py
closes #7 
adds new command `status`
adds `--sausage` option to `scan`
> added status command; added --sausage to scan command

- docs/api/commands.rst
- docs/overview/installation.rst
- recon/__init__.py
> added status command; updated install instructions; fixed typo

- recon/__init__.py
- recon/config.py
- recon/nmap.py
> added searchsploit to installable tools

- .gitattributes
> marked html files in tests/data as python for linguist

- README.md
- docs/overview/installation.rst
> Added apt update to installation instructions; closes #38

- Pipfile
- Pipfile.lock
> added black to dev reqs and pinned all reqs; closes #51 and #37

- pipeline/tools/amass.yaml
- pipeline/tools/aquatone.yaml
- pipeline/tools/go.yaml
- pipeline/tools/gobuster.yaml
- pipeline/tools/luigi-service.yaml
- pipeline/tools/masscan.yaml
- pipeline/tools/recursive-gobuster.yaml
- pipeline/tools/searchsploit.yaml
- pipeline/tools/seclists.yaml
- pipeline/tools/subjack.yaml
- pipeline/tools/tko-subs.yaml
- pipeline/tools/webanalyze.yaml
Redefine ~ to default home dir using join_path
- [N/A] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [N/A] Your PR description references the associated issue (i.e. fixes #123)
- [N/A] Documentation about your PR is included in docs/ and the README, as appropriate
- [N/A] New code is unit tested
- [N/A] New tests pass
> Changes commands to be more uniform/readable

- docs/index.rst
- docs/modifications/index.rst
- docs/modifications/new_scanner.rst
- docs/modifications/new_wrapper.rst
- [-] All python files are formatted using black
- [-] All flake8 checks pass
- [-] All existing tests pass
- [-] New code is unit tested
- [-] New tests pass
> Added docs on how to add a new scanner & tool definition; closes #43

- .github/workflows/pythonapp.yml
- .pre-commit-config.yaml
- Pipfile
- Pipfile.lock
- pipeline/recon-pipeline.py
- pipeline/recon/config.py
- pipeline/tools/amass.yaml
- pipeline/tools/go.yaml
- pipeline/tools/gobuster.yaml
- pipeline/tools/recursive-gobuster.yaml
- pipeline/tools/searchsploit.yaml
- pipeline/tools/seclists.yaml
- pipeline/tools/subjack.yaml
- pipeline/tools/tko-subs.yaml
- pipeline/tools/waybackurls.yaml
- pipeline/tools/webanalyze.yaml
- tests/test_tools_install/test_tools_install_command.py
- tests/utils.py
> added tests for new ci stage; restructured go tool installs

- pipeline/recon/web/subdomain_takeover.py
- pipeline/tools/tko-subs.yaml
> institued fix from discussion; closes #68

- .github/workflows/pythonapp.yml
- pipeline/tools/go.yaml
- tests/test_tools_install/test_tools_install_command.py
- tests/utils.py
> Troublehoot pipeline tool tests

- docs/overview/installation.rst
- pipeline/recon-pipeline.py
- pipeline/recon/__init__.py
- pipeline/recon/parsers.py
- pipeline/tools/amass.yaml
- pipeline/tools/aquatone.yaml
- pipeline/tools/go.yaml
- pipeline/tools/gobuster.yaml
- pipeline/tools/luigi-service.yaml
- pipeline/tools/masscan.yaml
- pipeline/tools/recursive-gobuster.yaml
- pipeline/tools/searchsploit.yaml
- pipeline/tools/seclists.yaml
- pipeline/tools/subjack.yaml
- pipeline/tools/tko-subs.yaml
- pipeline/tools/waybackurls.yaml
- pipeline/tools/webanalyze.yaml
- tests/test_tools_install/test_tools_install_command.py
- tests/utils.py
Fixes #45 by adding uninstall command.
> Uninstall command

- README.md
- docs/api/commands.rst
- docs/overview/installation.rst
- docs/overview/scheduler.rst
- docs/overview/visualization.rst
- docs/requirements.txt
- pipeline/recon-pipeline.py
- pipeline/recon/__init__.py
- pipeline/recon/parsers.py
- pipeline/tools/go.yaml
- tests/test_recon/test_parsers.py
- tests/test_shell/test_recon_pipeline_shell.py
- tests/test_tools_install/test_tools_install_command.py
> WIP: added tools command; closes #44

- pipeline/recon/amass.py
- pipeline/recon/helpers.py
- pipeline/recon/masscan.py
- pipeline/recon/nmap.py
- pipeline/recon/web/aquatone.py
- pipeline/recon/web/gobuster.py
- pipeline/recon/web/subdomain_takeover.py
- pipeline/recon/web/waybackurls.py
- pipeline/recon/web/webanalyze.py
- pipeline/recon/wrappers.py
- tests/test_recon/test_helpers.py
- tests/test_recon/test_masscan.py
- tests/test_shell/test_recon_pipeline_shell.py
- tests/test_web/test_webanalyze.py
> Limit tab completion of scan command to scans with installed components

- pipeline/recon/config.py
- pipeline/tools/go.yaml
> added support for 32bit go installations

- pipeline/recon-pipeline.py
> corrected searchsploit out of index list error

- Dockerfile
- README.md
- docs/overview/installation.rst
- [ X ] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [ X ] Your PR description references the associated issue (i.e. fixes #123)
- [ X ] Code is in its own branch
- [ X ] Branch name is related to the PR contents
- [ X ] PR targets master
- [ X ] All python files are formatted using black
- [ X ] All flake8 checks pass
- [ X ] All existing tests pass
- [ X ] Documentation about your PR is included in docs/ and the README, as appropriate
- [ X ] New code is unit tested
- [ X ] New tests pass
> Added Dockerfile. Updated docs accordingly. #62

- pipeline/recon-pipeline.py
- pipeline/recon/amass.py
- pipeline/recon/helpers.py
- pipeline/recon/masscan.py
- pipeline/recon/nmap.py
- pipeline/recon/web/aquatone.py
- pipeline/recon/web/gobuster.py
- pipeline/recon/web/subdomain_takeover.py
- pipeline/recon/web/waybackurls.py
- pipeline/recon/web/webanalyze.py
- pipeline/recon/wrappers.py
- tests/test_recon/test_amass.py
- tests/test_recon/test_helpers.py
- tests/test_recon/test_masscan.py
- tests/test_recon/test_nmap.py
- tests/test_web/test_aquatone.py
- tests/test_web/test_gobuster.py
- tests/test_web/test_subdomain_takeover.py
- tests/test_web/test_targets.py
- tests/test_web/test_waybackurls.py
- tests/test_web/test_webanalyze.py
Adds checks to determine if dependencies are installed before scanning. Notifies user via exception if dependencies are not installed. The purpose of this WIP PR is to receive feedback on re-design of the meets_requirements() function.
Testing needs some work
Closes #73
> Dependency Checking

- pipeline/recon/web/nuclei.py
> added nucleiscan skeleton

- .github/workflows/pythonapp.yml
- .pre-commit-config.yaml
- README.md
- docs/overview/installation.rst
- pipeline/recon-pipeline.py
- pipeline/recon/helpers.py
- pipeline/tools/amass.yaml
- pipeline/tools/aquatone.yaml
- pipeline/tools/exploitdb.yaml
- pipeline/tools/go.yaml
- pipeline/tools/gobuster.yaml
- pipeline/tools/loader.py
- pipeline/tools/luigi-service.yaml
- pipeline/tools/masscan.yaml
- pipeline/tools/recursive-gobuster.yaml
- pipeline/tools/searchsploit.yaml
- pipeline/tools/seclists.yaml
- pipeline/tools/subjack.yaml
- pipeline/tools/tko-subs.yaml
- pipeline/tools/waybackurls.yaml
- pipeline/tools/webanalyze.yaml
- tests/test_recon/test_helpers.py
- tests/test_shell/test_recon_pipeline_shell.py
- tests/test_tools_install/test_tools_install_command.py
- tests/test_web/test_gobuster.py
> removed tool_dict dependency, tests incomplete

- pipeline/recon/helpers.py
> removed unnecessary print
